### 올바른 Key로 요청
POST http://localhost:7000/auth/v1/verify
Authorization: ZQKSK AK eyJhbGciOiJSUzI1NiJ9
Content-Type: application/json

### 잘못된 Key로 요청
POST http://localhost:7000/auth/v1/verify
Authorization: ZQKSK AK1 eyJhbGciOiJSUzI1NiJ9
Content-Type: application/json

### 유효하지 않은 Key로 요청
POST http://localhost:7000/auth/v1/verify
Authorization: ZQKSK AK eyJhbGciOiJSUzI1NiJ
Content-Type: application/json